# Generated by Django 5.2.7 on 2025-11-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_carrito_card_alter_item_carrito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Descuento',
            new_name='Cupon',
        ),
    ]
